version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: factus_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=factus_user
      - POSTGRES_PASSWORD=factus_password
      - POSTGRES_DB=factus_db
    ports:
      - "5432:5432"
    volumes:
      # Esto guarda los datos en una carpeta local 'postgres_data'
      # Así no pierdes tus facturas si apagas el contenedor
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U factus_user -d factus_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Opcional: Interfaz gráfica web para ver la BD (tipo PHPMyAdmin pero para Postgres)
  pgadmin:
    image: dpage/pgadmin4
    container_name: factus_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@factus.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db